name: heyring_client
description: Heyring mobile client
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  intl: ^0.19.0
  flutter_localization: ^0.3.0
  uuid: ^4.5.1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
